name       : libxcvt
version    : 0.1.1
release    : 1
source     :
    - https://xorg.freedesktop.org/archive/individual/lib/libxcvt-0.1.1.tar.xz : 27ebce180d355f94c1992930bedb40a36f6d7312ee50bf7f0acbcd22f33e8c29
license    : MIT
component  : xorg.library
summary    : VESA CVT standard timing modelines generator.
description: |
    libxcvt is a library providing a standalone version of the X server implementation of the VESA CVT standard timing modelines generator.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
